environment: default

replicaCount: 1

image:
  repository: ghcr.io/oluquejs/silly-cats
  tag: "1.0.0"
  digest: ""

ingress:
  host: desafio.bonam.cc

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi