environment: prod

replicaCount: 2

image:
  digest: "sha256:52721af8a7597e14f04ef885d8496a595b1355e31e18fab96050d952b361b123"

ingress:
  host: desafio.bonam.cc
  tls:
    enabled: true
    secretName: silly-cats-prod-tls

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 15