environment: prod

replicaCount: 2

image:
  digest: "sha256:8a6ca52ba1515e5230ed41135bc13493b9816f334ce6f6e012449def24015d9f"

ingress:
  host: desafio.bonam.cc
  tls:
    enabled: true
    clusterIssuer: letsencrypt-prod
    secretName: silly-cats-prod-tls

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  initialDelaySeconds: 15
  periodSeconds: 15