environment: dev

image:
  digest: "sha256:8a6ca52ba1515e5230ed41135bc13493b9816f334ce6f6e012449def24015d9f"

ingress:
  enabled: true
  host: desafio.bonam.cc
  path: /dev

  stripPrefix:
    enabled: true
    name: strip-dev
    prefixes:
      - /dev

  tls:
    enabled: true
    clusterIssuer: letsencrypt-prod
    secretName: silly-cats-dev-tls