apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: portainer
  namespace: argocd
spec:
  description: Portainer Cluster K3s
  sourceRepos:
  - https://portainer.github.io/k8s/
  destinations:
    - server: https://kubernetes.default.svc
      namespace: portainer
  clusterResourceWhitelist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"