apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: silly-cats-ing
  namespace: silly-cats-ns
spec:
  ingressClassName: traefik
  rules:
  - host: silly-cats.k8s.orb.local #! Temp with my orbstack local dns
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: silly-cats-svc
            port:
              number: 80